[package]
name = "moltflip"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "moltflip"

[features]
no-entrypoint = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
